# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Python Virtual Enviornment
        run: |
          python -m venv venv

      - name: Install build dependencies
        run: |
          source venv/bin/activate
          pip install flake8 pytest requests toml
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install module and dependencies
        run: |
          source venv/bin/activate
          pip install .

      - name: Lint with flake8
        run: |
          source venv/bin/activate
          flake8 ./src --config ./.github/workflows/tox.ini

      - name: Test with pytest
        run: |
          source venv/bin/activate
          pytest
